dist: xenial
language: go
sudo: required

go:
  - "1.12.x"

services:
  - docker

install:
  - export GO111MODULE=on
  - go mod download
  - php -v
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php composer.phar install --no-interaction --prefer-source

before_script:
  - go build -o tests/go-client tests/go-client.go
  - ./tests/go-client serve -c tests/.rr.yaml &

script:
  - vendor/bin/spiral-cs check src tests
  - go test -v -race -cover -coverprofile=broadcast.txt -covermode=atomic
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - curl https://codecov.io/bash -o codecov-bash
  - chmod +x codecov-bash
  - ./codecov-bash -f broadcast.txt
  - ./codecov-bash -f coverage.xml

jobs:
  include:
    - stage: Test
      env: "PHP=7.2"
      before_install:
        - cd tests
        - docker-compose up -d
        - cd ..
        - sudo add-apt-repository -y ppa:ondrej/php
        - sudo apt-get update
        - sudo apt-get install -y php7.2-cli php7.2-mbstring php7.2-xml php7.2-xdebug
        - sudo cp `which php7.2` `which php`
    - stage: Test
      env: "PHP=7.3"
      before_install:
        - cd tests
        - docker-compose up -d
        - cd ..
        - sudo add-apt-repository -y ppa:ondrej/php
        - sudo apt-get update
        - sudo apt-get install -y php7.3-cli php7.3-mbstring php7.3-xml php7.3-xdebug
        - sudo cp `which php7.3` `which php`
